#include <QCoreApplication>
#include <QFile>
#include <QDebug>
#include <QTextStream>
int main(int argc, char *argv[])
{
    QCoreApplication a(argc, argv);
    QString filename = "D:/NOC/Tugas Padli/Produktif/Belajar C++/teslagi/testt.txt";
    QFile file(filename);

    if(file.open(QIODevice::WriteOnly | QIODevice::Text)){
        QTextStream out(&file);
        out<<"This file is generated by qt\n";
        qDebug()<<"Data added , please go to directory.";
        file.close();

        return 0;
    }else{
        qDebug()<<"Error , data failed to add to file !";
    }
}
